name: CI
on:
  push:
jobs:
  # Job that runs all go tests.
  go-test:
    runs-on: ubuntu-latest
    container: "golang:1.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /gocache
          # Store a cache for the current branch
          key: go-cache-${{ github.ref }}
          # If it is not found or it is the first run, use master's
          # test cache.
          restore-keys: |
            go-cache-refs/heads/master
      - name: Run tests
        run: make test

  # Job that runs gofumports on all go source files. Will fail if any formatting changes
  # have not been committed.
  go-format:
    runs-on: ubuntu-latest
    container: "golang:1.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install tools
        run: make install-tools
      - name: Format
        run: make format
      - name: Check for changes
        run: make has-changes

  # Job that runs golangci-lint on all go source files. Will fail on any linting
  # errors.
  go-lint:
    runs-on: ubuntu-latest
    container: "golang:1.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install generators
        run: make install-tools
      - name: Run linters
        run: make lint

  # Job that ensures all dependencies are added to the go.mod and go.sum files
  go-mod:
    runs-on: ubuntu-latest
    container: "golang:1.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Tidy
        run: make modules
      - name: Check for changes
        run: make has-changes
